name: Compile MATLAB App
on: [push]
jobs:
  build:
    name: Compile MATLAB app for various Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0

      - name: Run MATLAB command
        uses: matlab-actions/run-command@v0
        with:
            command: compile_app